api_type: "ollama"  # or azure / ollama / open_llm etc. Check LLMType for more options
model: "qwen2.5:7b-instruct"  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview qwen2.5:7b-instruct
base_url: "http://192.168.0.17:11434/api"
